---
- name: Preconfigure AWS Hosts with Appliciation
  hosts: web_servers

  tasks:
  - name: Install required software
    ansible.builtin.yum:
      name: "{{ item }}"
      state: latest
    become: true
    loop:
    - git
    - docker
  
  - name: Gather list of installed services
    ansible.builtin.service_facts:
  
  - name: Configure Docker
    block:
    - name: Start Docker and make persistent
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Adding excisting user to group docker
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: yes
    
    - name: Download Docker-Compose
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: "0755"
    
    - name: Copy docker-compose.yml files
      ansible.builtin.copy:
        src: docker-compose.yml
        dest: docker-compose.yml
        owner: ec2-user
        group: ec2-user
    
    - name: Clone app repo
      ansible.builtin.git:
        repo: https://github.com/docker/getting-started.git
        dest: ~/getting-started
        clone: true
        update: true
      become_user: ec2-user
    
    - name: Copy app folder from repo
      copy:
        src: ~/getting-started/app/
        remote_src: true
        dest: ~/app
      become_user: ec2-user
    
    - name: Check if app started
      command: docker ps
      register: docker_ps
    
    - name: Start app
      command: /usr/local/bin/docker-compose up -d
      when: "'ec2-user-app-1' not in docker_ps.stdout"

    when: "'docker.service' in services"
    become: true
